namespace Raybod.SCM.Domain.Enum
{
    public enum SCMFormPermission
    {
        Contract = 1,
        DocumentList = 2,
        Document = 3,
        DocumentRevision = 4,
        Bom = 5,
        MRP = 6,
        PurchaseRequest = 7,
        RFP = 8,
        EvaluationPlan = 9,
        RequestTechProposal = 10,
        ClariTechBefore = 11,
        ReceiveTechProposal = 12,
        ClariTechAfter = 13,
        RequestCommercialProposal = 14,
        ClariCommercialBefore = 15,
        ReceiveCommercialProposal = 16,
        ClariCommercialAfter = 17,
        TBE = 18,
        CBE = 19,
        RFPSupplierSelection = 20,
        PrContract = 21,
        PO = 22,
        POTracking = 22,
        POPReParationEngineering = 23,
        POPReParationConstruction = 24,
        POPReParationPurchase = 25,
        POPReParationOther = 26,
        Batch = 27,
        Pack = 28,
        POTransportation = 29,
        POClearancePort = 30,
        POReportDeliverProducts = 31,
        POFinancialObserver = 32,
        Transportation = 33,
        ClearancePort = 34,
        WarehouseManagement = 35,
        Receipt = 36,
        Invoice = 37,
        Payment = 38,
        FinancialAccount = 39,
    }
}
